### PR TITLE
CelAction Plugin

### PR DESCRIPTION
**Pull request by tokejepsen**
This is the production proven CelAction plugin used at Cloth Cat Animation.

### CODE REVIEW

**Comment by tokejepsen** [comment]
I don't quite get the CI errors? Seems to be with the file name?

**Comment by mjnowen** [comment]
It's just PEP8 compliance. I will ask if we can calm it down a bit in the future.

**Comment by tokejepsen** [comment]
I can change the filename if needed. Was just following other submission scripts naming convention.

**Comment by mjnowen** [comment]
All of our plugins have now been updated to support Deadline 8 onwards. With that in mind, the *.dlinit files was deprecated.:
http://docs.thinkboxsoftware.com/products/deadline/8.0/1_User%20Manual/manual/application-plugins.html#param-file

I'm not sure what we want to do about customers running older versions who still wish to open source plugins. I will discuss with the team later today.

**Comment by RandomInsano** [comment]
It's actually not the name of the file but the whitespace and comments being grumpy. If you use the 'details' link you can see some of the issues here:

https://travis-ci.org/ThinkboxSoftware/Deadline/jobs/148032743#L147

If you want to test on your local machine, install pep8 by running `pip install pep8` if pip is available and running it with `pep8 --count --ignore=W293,E501 CelActionSubmission.py`

**Comment by tokejepsen** [comment]
@RandomInsano didn't know you guys were using PEP8 now, since all your other plugins don't?

**Comment by tokejepsen** [comment]
Woot woot😀

**Pull request merged**
