### PR TITLE
Event Script plugin

### PR DESCRIPTION
**Pull request by tokejepsen**
This is an event plugin that executes a script specified in the job parameters.

### CODE REVIEW

**Comment by jamesthinkbox** [comment]
Thanks for this contribution!  A couple small things...

1) Please fix the CI checks that failed.
2) Please add a README.md that describes the script and how it is used,

**Comment by tokejepsen** [comment]
Why did it fail on the print statement? Is the CI on python 3?

**Comment by jamesthinkbox** [comment]
Our CI checks against both Python 2.7 and 3.  In Python 3, the content of a print statement must be enclosed in parentheses.  Parentheses are backwards compatible to 2.x, so should work for both.

**Comment by tokejepsen** [comment]
That should do it :)

**Comment by jamesthinkbox** [comment]
Thanks!  I'm going to merge this now.

I do have a couple of recommendations for improvements:  After retrieving the script's path from the ExtraInfo, run a path mapping on it to convert it to the Slave's current platform (so that the script works cross-platform).  After doing the path mapping, confirm that the script file is reachable from the Slave before calling execfile().

**Comment by tokejepsen** [comment]
> I do have a couple of recommendations for improvements: After retrieving the script's path from the ExtraInfo, run a path mapping on it to convert it to the Slave's current platform (so that the script works cross-platform). After doing the path mapping, confirm that the script file is reachable from the Slave before calling execfile().

All good suggestions :) Unfortunately I can't test that currently, so maybe it should be in an issue?

**Comment by jamesthinkbox** [comment]
Understood.  I've created #39 to keep track of it.  Thanks again for this nice addition.

**Pull request merged**
